### ISSUE TITLE
Bug with the new update

### ISSUE THREAD

**Issue by Iphodien** [powerkasi/FS22_WoodHarvesterMeasurement#1]
Hello,

With the new update  the configuration of wood cut lenght is KO.

Tested with a new save on Piney Run only Manuel Cutter and this mod with vanilla and mod machinery.

Thanks.

**Comment by powerkasi** [comment]
Closed as duplicate for https://github.com/powerkasi/FS22_WoodHarvesterMeasurement/issues/2
